# Generated by Django 5.0.4 on 2024-05-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicplaylist',
            old_name='play_list',
            new_name='playlist',
        ),
    ]
